// <auto-generated />
using System;
using Allfit_Webproject.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Allfit_Webproject.Server.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260518071942_AbonnementTable")]
    partial class AbonnementTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Aanbod", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("BeschrijvingBegeleiding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<bool>("ExtraBegeleiding")
                        .HasColumnType("bit");

                    b.Property<int>("SportschoolId")
                        .HasColumnType("int");

                    b.Property<int?>("TrainerId")
                        .HasColumnType("int");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("TrainerId");

                    b.ToTable("Aanbod");

                    b.HasDiscriminator().HasValue("aanbod");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Abonnement", b =>
                {
                    b.Property<int>("LidID")
                        .HasColumnType("int");

                    b.Property<string>("MollieID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("DateEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateStart")
                        .HasColumnType("date");

                    b.Property<int>("LidmaatschapID")
                        .HasColumnType("int");

                    b.HasKey("LidID", "MollieID");

                    b.ToTable("Abonnement");
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.ContactFormulier", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("beschrijving")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("ContactFormulieren");
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Faciliteit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("SportschoolId")
                        .HasColumnType("int");

                    b.Property<string>("beschrijving")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("SportschoolId");

                    b.ToTable("Faciliteiten");
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Gebruiker", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefoonnummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wachtwoord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Gebruiker");

                    b.HasDiscriminator().HasValue("Gebruiker");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Lidmaatschap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beschrijving")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duur")
                        .HasColumnType("int");

                    b.Property<double>("Inschrijfgeld")
                        .HasColumnType("float");

                    b.Property<double>("Lidmaatschapgeld")
                        .HasColumnType("float");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opzegtermijn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Lidmaatschap");
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Openingstijd", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("SportschoolId")
                        .HasColumnType("int");

                    b.Property<string>("dag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tijdOpen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tijdSluit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("SportschoolId");

                    b.ToTable("Openingstijden");
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Sportschool", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Sportscholen");
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Fitness", b =>
                {
                    b.HasBaseType("Allfit_Webproject.Server.Models.Aanbod");

                    b.HasDiscriminator().HasValue("fitness");
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Groepsles", b =>
                {
                    b.HasBaseType("Allfit_Webproject.Server.Models.Aanbod");

                    b.Property<string>("duur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("niveau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("groepsles");
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Kickboks", b =>
                {
                    b.HasBaseType("Allfit_Webproject.Server.Models.Aanbod");

                    b.Property<string>("doelgroep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("kickboks");
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Lid", b =>
                {
                    b.HasBaseType("Allfit_Webproject.Server.Models.Gebruiker");

                    b.Property<string>("adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("geboortedatum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("huisnummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActief")
                        .HasColumnType("bit");

                    b.Property<int>("lidmaatschapId")
                        .HasColumnType("int");

                    b.Property<string>("postcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("woonplaats")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("lid");
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Trainer", b =>
                {
                    b.HasBaseType("Allfit_Webproject.Server.Models.Gebruiker");

                    b.Property<string>("specialisatie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("trainer");
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Aanbod", b =>
                {
                    b.HasOne("Allfit_Webproject.Server.Models.Trainer", "trainer")
                        .WithMany()
                        .HasForeignKey("TrainerId");

                    b.Navigation("trainer");
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Faciliteit", b =>
                {
                    b.HasOne("Allfit_Webproject.Server.Models.Sportschool", "Sportschool")
                        .WithMany("alleFaciliteiten")
                        .HasForeignKey("SportschoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sportschool");
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Openingstijd", b =>
                {
                    b.HasOne("Allfit_Webproject.Server.Models.Sportschool", "Sportschool")
                        .WithMany("openingstijdenSportschool")
                        .HasForeignKey("SportschoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sportschool");
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Sportschool", b =>
                {
                    b.Navigation("alleFaciliteiten");

                    b.Navigation("openingstijdenSportschool");
                });
#pragma warning restore 612, 618
        }
    }
}
