// <auto-generated />
using System;
using Allfit_Webproject.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Allfit_Webproject.Server.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Aanbod", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("BeschrijvingBegeleiding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<bool>("ExtraBegeleiding")
                        .HasColumnType("bit");

                    b.Property<int>("SportschoolId")
                        .HasColumnType("int");

                    b.Property<int?>("TrainerId")
                        .HasColumnType("int");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("TrainerId");

                    b.ToTable("Aanbod");

                    b.HasDiscriminator().HasValue("aanbod");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Abonnement", b =>
                {
                    b.Property<int>("LidID")
                        .HasColumnType("int");

                    b.Property<string>("MollieID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("DateEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateStart")
                        .HasColumnType("date");

                    b.Property<int>("LidmaatschapID")
                        .HasColumnType("int");

                    b.HasKey("LidID", "MollieID");

                    b.ToTable("Abonnement");
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.ContactFormulier", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("aangemaaktOp")
                        .HasColumnType("datetime2");

                    b.Property<string>("beschrijving")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("naam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("titel")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("id");

                    b.ToTable("ContactFormulieren");
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Doel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("actief")
                        .HasColumnType("bit");

                    b.Property<string>("beschrijving")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Doelen", (string)null);
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Faciliteit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("SportschoolId")
                        .HasColumnType("int");

                    b.Property<string>("beschrijving")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("SportschoolId");

                    b.ToTable("Faciliteiten");
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Form", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bericht")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefoon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Form");
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Gebruiker", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefoonnummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wachtwoord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Gebruiker");

                    b.HasDiscriminator().HasValue("Gebruiker");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.GebruikerDoel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("aangemaaktOp")
                        .HasColumnType("datetime2");

                    b.Property<int>("doelId")
                        .HasColumnType("int");

                    b.Property<int>("gebruikerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("gewijzigdOp")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("doelId");

                    b.HasIndex("gebruikerId")
                        .IsUnique();

                    b.ToTable("GebruikerDoelen", (string)null);
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Inschrijving", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ExtraBegeleiding")
                        .HasColumnType("bit");

                    b.Property<int>("LesId")
                        .HasColumnType("int");

                    b.Property<int>("LidId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LesId");

                    b.HasIndex("LidId");

                    b.ToTable("Inschrijvingen");
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Les", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AanbodId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxDeelnemers")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Tijd")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("AanbodId");

                    b.ToTable("Lessen");
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Lidmaatschap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beschrijving")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duur")
                        .HasColumnType("int");

                    b.Property<double>("Inschrijfgeld")
                        .HasColumnType("float");

                    b.Property<double>("Lidmaatschapgeld")
                        .HasColumnType("float");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opzegtermijn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Lidmaatschap");
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Openingstijd", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("SportschoolId")
                        .HasColumnType("int");

                    b.Property<string>("dag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tijdOpen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tijdSluit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("SportschoolId");

                    b.ToTable("Openingstijden");
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Proefles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LesID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SportschoolID")
                        .HasColumnType("int");

                    b.Property<string>("Telefoon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LesID");

                    b.HasIndex("SportschoolID");

                    b.ToTable("Proefles");
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Sportschool", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Sportscholen");
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Voedingsschema", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("beschrijving")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("doelId")
                        .HasColumnType("int");

                    b.Property<string>("titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("doelId");

                    b.ToTable("Voedingsschemas", (string)null);
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.VoedingsschemaRegel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("advies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maaltijdMoment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("voedingsschemaId")
                        .HasColumnType("int");

                    b.Property<int>("volgorde")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("voedingsschemaId");

                    b.ToTable("VoedingsschemaRegels", (string)null);
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Fitness", b =>
                {
                    b.HasBaseType("Allfit_Webproject.Server.Models.Aanbod");

                    b.HasDiscriminator().HasValue("fitness");
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Groepsles", b =>
                {
                    b.HasBaseType("Allfit_Webproject.Server.Models.Aanbod");

                    b.Property<string>("duur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("niveau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("groepsles");
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Kickboks", b =>
                {
                    b.HasBaseType("Allfit_Webproject.Server.Models.Aanbod");

                    b.Property<string>("doelgroep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("kickboks");
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Lid", b =>
                {
                    b.HasBaseType("Allfit_Webproject.Server.Models.Gebruiker");

                    b.Property<string>("adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("geboortedatum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("huisnummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActief")
                        .HasColumnType("bit");

                    b.Property<int>("lidmaatschapId")
                        .HasColumnType("int");

                    b.Property<string>("postcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("woonplaats")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Lid");
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Trainer", b =>
                {
                    b.HasBaseType("Allfit_Webproject.Server.Models.Gebruiker");

                    b.Property<string>("specialisatie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("trainer");
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Aanbod", b =>
                {
                    b.HasOne("Allfit_Webproject.Server.Models.Trainer", "trainer")
                        .WithMany()
                        .HasForeignKey("TrainerId");

                    b.Navigation("trainer");
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Faciliteit", b =>
                {
                    b.HasOne("Allfit_Webproject.Server.Models.Sportschool", "Sportschool")
                        .WithMany("alleFaciliteiten")
                        .HasForeignKey("SportschoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sportschool");
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.GebruikerDoel", b =>
                {
                    b.HasOne("Allfit_Webproject.Server.Models.Doel", "doel")
                        .WithMany()
                        .HasForeignKey("doelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Allfit_Webproject.Server.Models.Gebruiker", "gebruiker")
                        .WithMany()
                        .HasForeignKey("gebruikerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("doel");

                    b.Navigation("gebruiker");
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Inschrijving", b =>
                {
                    b.HasOne("Allfit_Webproject.Server.Models.Les", "Les")
                        .WithMany()
                        .HasForeignKey("LesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Allfit_Webproject.Server.Models.Lid", "Lid")
                        .WithMany()
                        .HasForeignKey("LidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Les");

                    b.Navigation("Lid");
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Les", b =>
                {
                    b.HasOne("Allfit_Webproject.Server.Models.Aanbod", "Aanbod")
                        .WithMany()
                        .HasForeignKey("AanbodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aanbod");
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Openingstijd", b =>
                {
                    b.HasOne("Allfit_Webproject.Server.Models.Sportschool", "Sportschool")
                        .WithMany("openingstijdenSportschool")
                        .HasForeignKey("SportschoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sportschool");
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Proefles", b =>
                {
                    b.HasOne("Allfit_Webproject.Server.Models.Aanbod", "Les")
                        .WithMany()
                        .HasForeignKey("LesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Allfit_Webproject.Server.Models.Sportschool", "Sportschool")
                        .WithMany()
                        .HasForeignKey("SportschoolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Les");

                    b.Navigation("Sportschool");
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Voedingsschema", b =>
                {
                    b.HasOne("Allfit_Webproject.Server.Models.Doel", "doel")
                        .WithMany("voedingsschemas")
                        .HasForeignKey("doelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("doel");
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.VoedingsschemaRegel", b =>
                {
                    b.HasOne("Allfit_Webproject.Server.Models.Voedingsschema", "voedingsschema")
                        .WithMany("regels")
                        .HasForeignKey("voedingsschemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("voedingsschema");
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Doel", b =>
                {
                    b.Navigation("voedingsschemas");
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Sportschool", b =>
                {
                    b.Navigation("alleFaciliteiten");

                    b.Navigation("openingstijdenSportschool");
                });

            modelBuilder.Entity("Allfit_Webproject.Server.Models.Voedingsschema", b =>
                {
                    b.Navigation("regels");
                });
#pragma warning restore 612, 618
        }
    }
}
